repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-aws-credentials
    -   id: detect-private-key
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
-   repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
    -   id: black
        args: [--line-length=120]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: "v0.961"
#     hooks:
#     -   id: mypy
-   repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
# -   repo: https://github.com/pycqa/isort
#     rev: "5.10.1"
#     hooks:
#       - id: isort
#         args: [--line-length=120]
# -   repo: https://github.com/pre-commit/mirrors-autopep8
#     rev: "v1.6.0"
#     hooks:
#     -   id: autopep8
#         args: ["--max-line-length=120"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.9.0"
    hooks:
    -   id: python-use-type-annotations
    # -   id: python-no-log-warn
    -   id: python-no-eval
    -   id: python-check-mock-methods
    -   id: python-check-blanket-noqa
    -   id: python-check-blanket-type-ignore
    -   id: text-unicode-replacement-char
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.37.1
    hooks:
    -   id: pyupgrade
# -   repo: https://github.com/PyCQA/bandit
#     rev: "1.7.4"
#     hooks:
#     -   id: bandit
# -   repo: https://github.com/PyCQA/pydocstyle
#     rev: "6.1.1"
#     hooks:
#     -   id: pydocstyle
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets
