CREATE TABLE controle_transacao (
   CTTR_ID NUMERIC(10) PRIMARY key NOT NULL,
   CTTR_NM VARCHAR(50) NOT NULL,
   CTTR_ST NUMERIC(1) NOT NULL,
   CTTR_HR_DT_START_PROCESS DATE,
   CTTR_HR_DT_END_PROCESS DATE,
   CTTR_QT_PROCESSED_RECORD NUMERIC,
   CTTR_DT_INSERT DATE not null,
   CTTR_USER_INSERT VARCHAR(30) not null,
   CTTR_DT_UPDATE DATE,
   CTTR_USER_UPDATE VARCHAR(30),
   CTTR_DT_DELETE DATE,
   CTTR_USER_DELETE VARCHAR(30)
);

CREATE TABLE controle_transacao_detalhe (
   CTTD_ID NUMERIC(10) PRIMARY KEY NOT NULL,
   CTTR_ID NUMERIC(10) NOT NULL,
   CTTD_NM VARCHAR(50),
   CTTD_ST NUMERIC(1) NOT NULL,
   CTTD_HR_DT_START_TRANSACTION DATE,
   CTTD_HR_DT_END_TRANSACTION NUMERIC,
   CTTD_DT_INSERT DATE,
   CTTD_QT_PROCESSED_RECORD NUMERIC,
   CTTD_USER_INSERT VARCHAR(30),
   CTTD_DT_UPDATE DATE,
   CTTD_USER_UPDATE VARCHAR(30),
   CTTD_DT_DELETE DATE,
   CTTD_USER_DELETE VARCHAR(30),
   CONSTRAINT fk_controle_transacao
      FOREIGN KEY(CTTR_ID)
	  REFERENCES controle_transacao(CTTR_ID)
);

CREATE TABLE controle_transacao_erro (
   CTTE_ID NUMERIC(10) PRIMARY KEY NOT NULL,
   CTTE_DS VARCHAR(200),
   CTTE_DT_INSERT DATE NOT NULL,
   CTTE_USER_INSERT VARCHAR(30) NOT NULL,
   CTTE_DT_UPDATE DATE,
   CTTE_USER_UPDATE VARCHAR(30),
   CTTE_DT_DELETE DATE,
   CTTE_USER_DELETE VARCHAR(30),
   CTTD_ID NUMERIC(10),
   CONSTRAINT fk_controle_transacao_detalhe
      FOREIGN KEY(CTTD_ID)
	  REFERENCES controle_transacao_detalhe(CTTD_ID)
);
